[package]
name = "cow_universe"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.9"
bevy_egui = "*" 
bevy-inspector-egui = "*"
quadtree_rs="*"
rand="*"